---
title: "教育研究技術的學習地圖"
author: 'JW Tsai'
date: '2021-07-02'
---


我心目中教育研究的技術（理論先不談），至少有下面四個面向：

- 科學計算
- 測量模型 (Descriptive models)
- 資料分析 (Explanatory models)
- 程式編寫

所以這個 blog 基本上也會圍繞著這些主題來寫。
如果每一篇只能有 3 個核心主題的話，你會把哪些主題列為核心？？



## 計算篇

我心目中研究領域還是有 data analytics 跟 data science/engineering 之分的。教育研究的 data analytics 的關心重點在業務，模型只是一種做研究的工具，能力上大約做到可以跑模型、解釋資料（大部分量化研究人員都能做到這邊）。然後其實教育研究領域的模型都不會太難（頂多到多變、multi-level, SEM的程度），也幾乎都有現成套裝工具可以跑，所以其實業務理解可能更重要。

但是教育研究的 data science or engineering 的關心重點就是在模型（方法）本身。所以我心目中他除了跑（一般/進階）模型之外，至少要有幾種能力：

- 調整/比較模型、
- 做數據實驗（模擬研究）、
- 發展新的方法、整合數種方法

### Core Topics
```
1) Essential Computing Skills
2) Stat Exp
3) Simulation
```

### Book list：

- Pfaff, T. (2019). R for College Mathematics and Statistics. CRC.
- Will H. Moore, David A. Siegel. (). A Mathematics Course for Political and Social Research.
- Rizzo, M. L. (2019). Statistical Computing with R, 2/e. CRC Press.
- James Patrick Howard. (). Computational Methods for Numerical Analysis with R.
- Paul Gerrard, Radia M. Johnson. (). Mastering Scientific Computing with R 
- Sheldon Ross. (). Simulation, 5/e
- Christian Robert, George Casella (auth.) (). Introducing Monte Carlo Methods with R
- Simon N. Wood. (). Core Statistics


關於


## 測量篇


根據 Klaas Sijtsma, L. Andries van der Ark. (2020). 的書，有大概幾種類型：

- CTT and FA
- <mark> Non-parameter IRT </mark>
- Parameter IRT
- LCA and CDM
- Other Models: Pairwise Comparison, Proximity, Response Time, and Network Models

### Core Topics
```
1) FA
2) IRT
3) CDM
```

### Book list：

- Klaas Sijtsma, L. Andries van der Ark. (2020). Measurement Models for Psychological Attributes.


## 分析篇


### Core Topics

```
1) Survey data
2) longitudinal/repeated measurured data
3) GLM (Explanatory IRT, SEM, ...)
```
- 實驗設計？


## 程式篇









